repos:
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.5.0  # Use the version of ESLint you need
  #   hooks:
  #     - id: eslint
  #       additional_dependencies:
  #         - "@typescript-eslint/eslint-plugin@latest"
  #         - "@typescript-eslint/parser@latest"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Use the version of Prettier you need
    hooks:
      - id: prettier
        additional_dependencies: []
