// imports
import App from '@/App.vue'
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowRotateLeft,
  faArrowUpRightFromSquare,
  faAtom,
  faBell,
  faBug,
  faBowlRice,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faClipboardCheck,
  faCircle,
  faClock,
  faCoins,
  faDatabase,
  faDice,
  faExclamationTriangle,
  faEye,
  faFaceSmile,
  faFlagCheckered,
  faFolderOpen,
  faForward,
  faGamepad,
  faGauge,
  faGears,
  faGlobe,
  faHourglass,
  faHouse,
  faIndustry,
  faInfoCircle,
  faKeyboard,
  faKhanda,
  faLink,
  faList,
  faLock,
  faMagnifyingGlass,
  faMedal,
  faPenNib,
  faPlay,
  faPlus,
  faPause,
  faPauseCircle,
  faPeopleGroup,
  faPlayCircle,
  faQuestion,
  faRandom,
  faRobot,
  faRotateRight,
  faUnlink,
  faScrewdriverWrench,
  faSpinner,
  faSquarePlus,
  faTimeline,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faUserTie,
  faWalkieTalkie,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import * as vueshortkey from 'vue3-shortkey'

// use fontawesome icons
library.add(
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowRotateLeft,
  faArrowUpRightFromSquare,
  faAtom,
  faBell,
  faBowlRice,
  faBug,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faClipboardCheck,
  faCircle,
  faClock,
  faCoins,
  faDatabase,
  faDice,
  faExclamationTriangle,
  faEye,
  faFaceSmile,
  faFlagCheckered,
  faFolderOpen,
  faForward,
  faGamepad,
  faGauge,
  faGears,
  faGlobe,
  faHourglass,
  faHouse,
  faIndustry,
  faInfoCircle,
  faKeyboard,
  faKhanda,
  faLink,
  faList,
  faLock,
  faMagnifyingGlass,
  faMedal,
  faPenNib,
  faPlay,
  faPlus,
  faPause,
  faPauseCircle,
  faPeopleGroup,
  faPlayCircle,
  faQuestion,
  faRandom,
  faRobot,
  faRotateRight,
  faUnlink,
  faScrewdriverWrench,
  faSpinner,
  faSquarePlus,
  faTimeline,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faUserTie,
  faWalkieTalkie,
  faXmark,
)

// create the app
const app = createApp(App)
app.component('font-awesome-icon', FontAwesomeIcon)
app.use(createPinia())
app.use(vueshortkey)
app.mount('#app')
