import App from './App.vue'
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowDown,
  faArrowRight,
  faBell,
  faBowlRice,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faClock,
  faCoins,
  faDice,
  faExclamationTriangle,
  faEye,
  faFaceSmile,
  faFlagCheckered,
  faFolderOpen,
  faForward,
  faGamepad,
  faGears,
  faGlobe,
  faHourglass,
  faInfoCircle,
  faKhanda,
  faLink,
  faList,
  faLock,
  faPlay,
  faPlus,
  faPause,
  faPauseCircle,
  faPeopleGroup,
  faPlayCircle,
  faQuestion,
  faRandom,
  faRobot,
  faUnlink,
  faScrewdriverWrench,
  faSpinner,
  faSquarePlus,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faUserTie,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import * as vueshortkey from 'vue3-shortkey'

// use fontawesome icons
library.add(
  faArrowDown,
  faArrowRight,
  faBell,
  faBowlRice,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faClock,
  faCoins,
  faDice,
  faExclamationTriangle,
  faEye,
  faFaceSmile,
  faFlagCheckered,
  faFolderOpen,
  faForward,
  faGamepad,
  faGears,
  faGlobe,
  faHourglass,
  faInfoCircle,
  faKhanda,
  faLink,
  faList,
  faLock,
  faPlay,
  faPlus,
  faPause,
  faPauseCircle,
  faPeopleGroup,
  faPlayCircle,
  faQuestion,
  faRandom,
  faRobot,
  faUnlink,
  faScrewdriverWrench,
  faSpinner,
  faSquarePlus,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faUserTie,
  faXmark
)

// create the app
const app = createApp(App)
app.component('font-awesome-icon', FontAwesomeIcon)
app.use(createPinia())
app.use(vueshortkey)
app.mount('#app')
